version: 2
jobs:
  prep:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - run:
          name: Install FOSSA client
          command: curl -H 'Cache-Control:no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Upload FOSSA data
          command: fossa
          working_directory: ./

      - save_cache:
          key: npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
            - package-lock.json

  lint:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - run:
          name: Linting code
          command: npm run lint

  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - run:
          name: Running tests
          command: npm run test

  snyk:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package.json" }}
            - npm-deps-
      - run:
          name: Test using snyk
          command: npm run snyk
  

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - prep
      - lint:
          requires:
            - prep
      - test:
          requires:
            - prep
            - lint
      - snyk:
          requires:
            - prep
